config/routes.rb
Rails.application.routes.draw do

  resources :rides , only: [:create, :update]
  resources :requests
  resources :users, only: [:create]

  
  match '*path' => 'application#cors_preflight', :via => :options

  post 'auth' => 'authentications#create'
  delete 'auth' => 'authentications#destroy'

  post 'order' => 'requests#create'
  get 'order' => 'requests#show'
  patch '/request/action' => 'requests#action'

  post '/rides/start' => 'rides#create'
  patch '/rides/end' => 'rides#update'
  patch '/rides/location' => 'requests#updateloc'

  root 'users#index'

end

app/models/request.rb
class Request < ActiveRecord::Base
# accepts_nested_attributes_for
  belongs_to :request_status

  belongs_to :requester, :class_name => 'User', :foreign_key => 'requester_id'
  belongs_to :driver, :class_name => 'User', :foreign_key => 'driver_id'

  has_many :locations

end

app/controllers/requests_controller.rb
  require 'service'



  class RequestsController < ApplicationController

    # before_action :set_request, only: [:show, :edit, :update, :destroy]
    before_filter :ensure_authenticated_user

    # GET /requests
    # GET /requests.json
    def index
      @requests = Request.all
    end


    # POST /requests
    # POST /requests.json
    def create

      if current_user.user_type.name == 'driver'
       render json: { errors: 'Invalid user type' }, status: 401
       return
     end

     requests = Request.where(:requester_id => current_user.id).where(:status => 'onprogress') 
     
     if requests.size > 0
       render json: { errors: 'other request on progress' }, status: 401
       return
     end
     
     if current_user

      p 'request_params:',request_params
      requestparams = request_params.clone
      @request = Request.new

      @request[:requester_id] = current_user[:id]
      @request.status = 'onprogress'
      @request.save

      source_type = LocationType.find_by_name('source')
      destination_type = LocationType.find_by_name('destination')
      ontheway_type = LocationType.find_by_name('ontheway')
       # p 'is nil:' , (request_params == nil)
       p 'requests:', @request
       p 'request_param:'+ request_params.to_s
       # binding.pry

       source = Location.create(location_type: source_type, 
        latitude: request_params[:source][:latitude],
        longitude: request_params[:source][:longitude],
        request_id: @request[:id])
       source.save

       destination = Location.create(location_type: destination_type, 
        latitude: request_params[:destination][:latitude],
        longitude: request_params[:destination][:longitude], 
        request_id: @request[:id])
       destination.save 

         
        drivers  = User.where(' user_type_id = ? and (id IN (select user_id from activities where activity_type_id = ? or activity_type_id = ?)) ',
          UserType.find_by_name('driver')[:id],
          ActivityType.find_by_name('available')[:id],
          ActivityType.find_by_name('online')[:id]
          )
         
         # driver_activities = Activity.where("user_id IN (?) and (activity_type_id=? or activity_type_id=? ) ",
         #  User.where(:user_type_id => UserType.find_by_name('driver')[:id]).pluck(:id),
         #  ActivityType.find_by_name('available'),
         #  ActivityType.find_by_name('online'))
         
         require 'service'

         drivers.each do|driver|
           Service::PushService.notify_android( @request, driver.registration_device_id, nil)
         end
        
         render json: @request, status: 201 
         
         return 
       else

         render json: { errors: 'wrong user token.' }, status: 401
         return

       end

     end

     def show
      render json: Request.where(:status =>'onprogress')
    end

  #  def edit
  #   request_status = request_params[:update_status]
  # end
  # PATCH
  def updateloc

    if user_type == 'driver'

     last_location = Location.where(:request_id => request_params[:request_id]).where(:location_type => LocationType.find_by_name('ontheway'))
     last_location[:longitude => location[:longitude], :latitude => location[:latitude]]
     render json: @request, status: 201 

   else

     render json: { errors: 'wrong user token.' }, status: 401
     

   end
   return
 end


 def action

  if current_user.user_type.name == 'driver'

       #TODO => implement gcm push 
       p 'reqid:'+action_params[:request_id]  
       request = Request.find(action_params[:request_id]) 
       request.status = action_params[:acction_status]
       request.driver_id = current_user.id
       request.save
       # current_user.activity.activity_type = Activity.find_by_name('accept_request')
       
       render json: request        
     else

      render json: { errors: 'cannot process this action' }, status: 401      
    end

    return
  end


  private

  def request_params
    params.require(:request).permit( :source => [:longitude, :latitude], :destination => [:longitude, :latitude])
  end

  def action_params
    params.require(:driver_action).permit(:request_id,:acction_status)
  end

  def locat_params
    params.require(:location).permit(:longitude,:latitude)
  end

  def user_type
    current_user.user_type.name
  end

end

app/helpers/requests_helper.rb
module RequestsHelper
	
end

app/views/requests/_form.html.erb
<%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :requester_id %><br>
    <%= f.number_field :requester_id %>
  </div>
  <div class="field">
    <%= f.label :driver_id %><br>
    <%= f.number_field :driver_id %>
  </div>
  <div class="field">
    <%= f.label :source_id %><br>
    <%= f.number_field :source_id %>
  </div>
  <div class="field">
    <%= f.label :destination_id %><br>
    <%= f.number_field :destination_id %>
  </div>
  <div class="field">
    <%= f.label :request_status_id %><br>
    <%= f.text_field :request_status_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Requests</h1>

<table>
  <thead>
    <tr>
      <th>Requester</th>
      <th>Driver</th>
      <th>Source</th>
      <th>Destination</th>
      <th>Request status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.requester_id %></td>
        <td><%= request.driver_id %></td>
        <td><%= request.source_id %></td>
        <td><%= request.destination_id %></td>
        <td><%= request.request_status %></td>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path %>

app/views/requests/new.html.erb
<h1>New Request</h1>

<%= render 'form' %>

<%= link_to 'Back', requests_path %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Requester:</strong>
  <%= @request.requester_id %>
</p>

<p>
  <strong>Driver:</strong>
  <%= @request.driver_id %>
</p>

<p>
  <strong>Source:</strong>
  <%= @request.source_id %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @request.destination_id %>
</p>

<p>
  <strong>Request status:</strong>
  <%= @request.request_status %>
</p>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>