config/routes.rb
Rails.application.routes.draw do

  resources :rides , only: [:create, :update]
  resources :requests
  resources :users, only: [:create]

  
  match '*path' => 'application#cors_preflight', :via => :options

  post 'auth' => 'authentications#create'
  delete 'auth' => 'authentications#destroy'

  post 'order' => 'requests#create'
  get 'order' => 'requests#show'
  patch '/request/action' => 'requests#action'

  post '/rides/start' => 'rides#create'
  patch '/rides/end' => 'rides#update'
  patch '/rides/location' => 'requests#updateloc'

  root 'users#index'

end

app/models/ride.rb
class Ride < ActiveRecord::Base
  belongs_to :request
  
end

app/models/ride_type.rb
class RideType < ActiveRecord::Base
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  before_action :set_ride, only: [:show, :edit, :update, :destroy]

  before_filter :ensure_authenticated_user
  # GET /rides
  # GET /rides.json
  def index
    @rides = Ride.all
  end

  # GET /rides/1
  # GET /rides/1.json
  def show
  end

  # GET /rides/new
  def new
    @ride = Ride.new
  end

  # GET /rides/1/edit
  def edit
  end

  # POST /rides
  # POST /rides.json
  def create

    if current_user.user_type.name = 'driver'

      @ride = Ride.new(:request_id => ride_params[:request_id], :start_time => Time.now )
      
      @ride.save
      render json: @ride 
    else
      render json: { errors: 'cannot process this action' }, status: 401      
    end

    return 
    # @ride.ride_type = RideType.find_by_name(ride_params[:ride_type])  
    # respond_to do |format|

    #   if @ride.save
       
    #     # format.html { redirect_to @ride, notice: 'Ride was successfully created.' }
    #     format.json { render :show, status: :created, location: @ride }
    #   else
    #     # format.html { render :new }
    #     format.json { render json: @ride.errors, status: :unprocessable_entity }
    #   end
    # end

  end

  # PATCH/PUT /rides/1
  # PATCH/PUT /rides/1.json
  def update
    
   
    if current_user.user_type.name = 'driver'

       ride = Ride.find(ride_params[:id]) 
       # Ride.where(:request_id => ride_params[:request_id])
       ride.arrived_time = Time.now
       ride.save

      render json: ride 
    else
      render json: { errors: 'cannot process this action' }, status: 401      
    end

    return
    
  end

  # DELETE /rides/1
  # DELETE /rides/1.json
  def destroy
    @ride.destroy
    respond_to do |format|
      format.html { redirect_to rides_url, notice: 'Ride was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ride
      @ride = Ride.find(ride_params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ride_params
      params.require(:ride).permit(:id,:ride_type, :request_id, :action)
    end


  end

app/helpers/rides_helper.rb
module RidesHelper
end

app/views/rides/_form.html.erb
<%= form_for(@ride) do |f| %>
  <% if @ride.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ride.errors.count, "error") %> prohibited this ride from being saved:</h2>

      <ul>
      <% @ride.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :arrived_time %><br>
    <%= f.datetime_select :arrived_time %>
  </div>
  <div class="field">
    <%= f.label :location_id %><br>
    <%= f.text_field :location_id %>
  </div>
  <div class="field">
    <%= f.label :request_id %><br>
    <%= f.text_field :request_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rides/edit.html.erb
<h1>Editing Ride</h1>

<%= render 'form' %>

<%= link_to 'Show', @ride %> |
<%= link_to 'Back', rides_path %>

app/views/rides/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rides</h1>

<table>
  <thead>
    <tr>
      <th>Start time</th>
      <th>Arrived time</th>
      <th>Location</th>
      <th>Request</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rides.each do |ride| %>
      <tr>
        <td><%= ride.start_time %></td>
        <td><%= ride.arrived_time %></td>
        <td><%= ride.location %></td>
        <td><%= ride.request %></td>
        <td><%= link_to 'Show', ride %></td>
        <td><%= link_to 'Edit', edit_ride_path(ride) %></td>
        <td><%= link_to 'Destroy', ride, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ride', new_ride_path %>

app/views/rides/new.html.erb
<h1>New Ride</h1>

<%= render 'form' %>

<%= link_to 'Back', rides_path %>

app/views/rides/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start time:</strong>
  <%= @ride.start_time %>
</p>

<p>
  <strong>Arrived time:</strong>
  <%= @ride.arrived_time %>
</p>

<p>
  <strong>Location:</strong>
  <%= @ride.location %>
</p>

<p>
  <strong>Request:</strong>
  <%= @ride.request %>
</p>

<%= link_to 'Edit', edit_ride_path(@ride) %> |
<%= link_to 'Back', rides_path %>